### ISSUE TITLE
챗봇 생성_짧은 질문

### ISSUE THREAD

**Issue by hyeyoung-x** [pladata-encore/DA36-mini4-app3#5]
## 🌈 Success criteria

1. 전처리 완료된 데이터(PDF) 기반의 RAG 모델 생성 

## 👷 To-do

- [ ] 전처리 완료된 데이터 모델 돌려보기
- [ ] 질문 query 요약 과정 추가(장문의 질문 인식)
- [x] 긴 문장 인식(사례 및 판례 등)을 위한 하이퍼파라미터 조정
- [x] 프롬프트 수정 -> 질문에 대한 구조화된 답변 위함
- [x] 학습 전후 답변 차이 확인하기
- [x] 역할분담

## 🧶 Review

- 생각보다 법률 사례 인식하지 못함
- 사용자의 질문이 길어지면 답변의 정확도가 떨어짐
- 구조화된 답변을 위한 프롬프트 작성
