### ISSUE TITLE
데이터 전처리

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36-mini4-app3#7]
## 🌈 Success criteria

1. 수집한 데이터를 바로 활용할 수 있는 상태로 전처리한다.

## 👷 To-do

- [x] 할일 1 : pdf와 csv 파일을 각각 메모리에 업로드한다.
- [x] 할일 2 : pdf파일 중텍스트가 아닌 이미지 파일로만 되어 있는 파일들을 삭제한다.
- [x] 할일 3 : 중복된 문서를 삭제한다.
- [x] 할일 4: 각 페이지 내 중복 공백, 개행문자 등을 삭제한다.

**필요한 라이브러리 목록**
chardet : csv파일 인코딩방식 추출
